//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectedData.AzureSQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedInApiData
    {
        public System.Guid Id { get; set; }
        public string LinkedInUserId { get; set; }
        public string Profile { get; set; }
        public string Connections { get; set; }
        public string Interests { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
